# Generated by Django 3.2.4 on 2021-11-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('users', '0002_auto_20211122_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car',
            field=models.ManyToManyField(blank=True, to='cars.Car'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.shift'),
        ),
    ]
