# Generated by Django 3.2.4 on 2021-11-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211124_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='type',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
