# Generated by Django 3.2.10 on 2021-12-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211125_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='nic',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
