# Generated by Django 3.2.10 on 2021-12-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_driver_nic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='nic',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
