# Generated by Django 3.2.4 on 2021-12-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_driver_nic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='NIC',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
