# Generated by Django 3.2.10 on 2021-12-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_driver_nic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='NIC',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
