# Generated by Django 3.2.10 on 2021-12-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_driver_nic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='NIC',
        ),
    ]
