# Generated by Django 3.2.4 on 2021-11-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=10)),
                ('car_type', models.CharField(max_length=40)),
                ('date_bought', models.DateField()),
                ('date_put_to_use', models.DateField()),
                ('price', models.IntegerField()),
                ('kilometres_bought_with', models.FloatField(default=0)),
            ],
        ),
    ]
