# Generated by Django 3.2.4 on 2021-11-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='matricule',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
