# Generated by Django 3.2.4 on 2021-11-30 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_date_creaetd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='date_creaetd',
            new_name='date_created',
        ),
    ]
