# Generated by Django 3.2.4 on 2021-12-01 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_date_creaetd_car_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=6)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='CarDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catergrise', models.DecimalField(decimal_places=0, max_digits=6)),
                ('insurance', models.DecimalField(decimal_places=0, max_digits=6)),
                ('visite_technique', models.DecimalField(decimal_places=0, max_digits=6)),
                ('carte_bleu', models.DecimalField(decimal_places=0, max_digits=6)),
                ('license_de_transport', models.DecimalField(decimal_places=0, max_digits=6)),
                ('importe', models.DecimalField(decimal_places=0, max_digits=6)),
                ('other', models.DecimalField(decimal_places=0, default=0, max_digits=6)),
                ('description', models.TextField()),
                ('date_paid', models.DateField()),
                ('expiry_date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
