# Generated by Django 3.2.10 on 2021-12-08 22:58

import cars.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transaction_id',
            field=models.CharField(default=cars.utils.expense_transaction_id, editable=False, max_length=20, unique=True),
        ),
    ]
