# Generated by Django 3.2.10 on 2021-12-08 23:23

import cars.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_expense_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='transaction_id',
            field=models.CharField(default=cars.utils.revenue_transaction_id, editable=False, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='transaction_id',
            field=models.CharField(default=cars.utils.expense_transaction_id, editable=False, max_length=256, unique=True),
        ),
    ]
