# Generated by Django 3.2.10 on 2021-12-12 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20211209_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardocument',
            name='carte_bleu',
        ),
        migrations.RemoveField(
            model_name='cardocument',
            name='catergrise',
        ),
        migrations.RemoveField(
            model_name='cardocument',
            name='importe',
        ),
        migrations.RemoveField(
            model_name='cardocument',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='cardocument',
            name='license_de_transport',
        ),
        migrations.RemoveField(
            model_name='cardocument',
            name='other',
        ),
        migrations.RemoveField(
            model_name='cardocument',
            name='visite_technique',
        ),
        migrations.AddField(
            model_name='cardocument',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
