# Generated by Django 3.2.10 on 2021-12-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20211212_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardocument',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardocument',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
