# Generated by Django 3.2.10 on 2021-12-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20211219_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardocument',
            name='image',
            field=models.ImageField(default='image', upload_to='documents/images/'),
            preserve_default=False,
        ),
    ]
