# Generated by Django 3.2.10 on 2022-01-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('salary_for', models.CharField(max_length=200, null=True)),
                ('salary_for_id', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=256)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
