# Generated by Django 3.2.10 on 2022-01-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='advancement',
            field=models.BooleanField(default=False),
        ),
    ]
