# Generated by Django 3.2.10 on 2022-01-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_salary_advancement'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='month',
            field=models.CharField(default='January', max_length=16),
            preserve_default=False,
        ),
    ]
